version: '3.9'

services:
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_PROPERTIES=jobmanager.properties
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_PROPERTIES=taskmanager.properties  
  go-backend:
    container_name: go-backend
    image: ouzzkp/go-backend:1.0.0
    build: ./backend
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=go_db sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  react-frontend:
    container_name: react-frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src 
      - ./frontend/public:/app/public
      - ./frontend/node_modules:/app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - go-backend
  go-script:
    container_name: go-script
    image: ouzzkp/go-script:1.0.0
    build: ./script
    environment:
      BACKEND_URL: "http://go-backend:8080"
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"    
    volumes:
      - pgData:/var/lib/postgresql/data

volumes:
  pgData: {}